Fix compilation due to missing include
Fix:

backend_prepare.cpp:644:87: error: ‘ceil’ is not a member of ‘std’

by including cmath.

Signed-off-by: Tomi Valkeinen <tomi.valkeinen@ideasonboard.com>