backend: Fix compiler error due missing include
Include <cstdint> to fix compiler errors
backend/tiling/stages.cpp:68:46: error: ‘uint8_t’ was not declared in this scope
backend/tiling/rescale_stage.hpp:25:57: error: ‘uint8_t’ has not been declared

Signed-off-by: Jacopo Mondi <jacopo.mondi@ideasonboard.com>